-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.areas_funcion
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT areas_funcion_pkey PRIMARY KEY (id),
    CONSTRAINT areas_funcion_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.carreras
(
    id serial NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT carreras_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.citas
(
    id bigserial NOT NULL,
    usuario_mentee_id bigint NOT NULL,
    mentor_id bigint NOT NULL,
    fecha_programada date NOT NULL,
    hora_programada time without time zone NOT NULL,
    tema character varying(255) COLLATE pg_catalog."default",
    otro_texto text COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    fecha_realizada date,
    hora_realizada time without time zone,
    fecha_creacion timestamp without time zone DEFAULT now(),
    se_dio_en_dia_acordado boolean,
    calificacion_general integer,
    calificacion_utilidad integer,
    recomendaria_mentor integer,
    recordatorio_enviado boolean DEFAULT false,
    CONSTRAINT citas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.destacado_solicitudes
(
    id serial NOT NULL,
    mentor_perfil_id integer NOT NULL,
    status character varying COLLATE pg_catalog."default",
    fecha_solicitud timestamp with time zone DEFAULT now(),
    fecha_revision timestamp with time zone,
    notas_admin text COLLATE pg_catalog."default",
    CONSTRAINT destacado_solicitudes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.disponibilidad_mentor
(
    id serial NOT NULL,
    mentor_id integer NOT NULL,
    dia character varying COLLATE pg_catalog."default" NOT NULL,
    hora_inicio character varying COLLATE pg_catalog."default" NOT NULL,
    hora_fin character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT disponibilidad_mentor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.educacion_usuario
(
    id bigserial NOT NULL,
    usuario_id bigint NOT NULL,
    universidad character varying(255) COLLATE pg_catalog."default" NOT NULL,
    carrera character varying(255) COLLATE pg_catalog."default" NOT NULL,
    anio_inicio integer,
    anio_fin integer,
    CONSTRAINT educacion_usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grados_academicos
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT grados_academicos_pkey PRIMARY KEY (id),
    CONSTRAINT grados_academicos_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.instituciones
(
    id serial NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT instituciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mentor_area
(
    mentor_id bigint NOT NULL,
    area_id bigint NOT NULL,
    CONSTRAINT mentor_area_pkey PRIMARY KEY (mentor_id, area_id)
);

CREATE TABLE IF NOT EXISTS public.mentor_grado
(
    mentor_id bigint NOT NULL,
    grado_id bigint NOT NULL,
    CONSTRAINT mentor_grado_pkey PRIMARY KEY (mentor_id, grado_id)
);

CREATE TABLE IF NOT EXISTS public.mentor_sector
(
    mentor_id bigint NOT NULL,
    sector_id bigint NOT NULL,
    CONSTRAINT mentor_sector_pkey PRIMARY KEY (mentor_id, sector_id)
);

CREATE TABLE IF NOT EXISTS public.mentor_tema
(
    mentor_id bigint NOT NULL,
    tema_id bigint NOT NULL,
    nota character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT mentor_tema_pkey PRIMARY KEY (mentor_id, tema_id)
);

CREATE TABLE IF NOT EXISTS public.page_visits
(
    id serial NOT NULL,
    ip_address character varying COLLATE pg_catalog."default",
    country character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    path character varying COLLATE pg_catalog."default",
    user_agent character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT page_visits_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.perfiles_mentor
(
    id bigserial NOT NULL,
    usuario_id bigint NOT NULL,
    destacado boolean DEFAULT false,
    biografia text COLLATE pg_catalog."default",
    anio_egreso integer,
    horario_sugerido character varying(500) COLLATE pg_catalog."default",
    empresa character varying COLLATE pg_catalog."default",
    url_logo_empresa character varying COLLATE pg_catalog."default",
    bloqueado_destacado boolean DEFAULT false,
    CONSTRAINT perfiles_mentor_pkey PRIMARY KEY (id),
    CONSTRAINT perfiles_mentor_usuario_id_key UNIQUE (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.perfiles_usuario
(
    id bigserial NOT NULL,
    usuario_id bigint NOT NULL,
    genero character varying(20) COLLATE pg_catalog."default",
    telefono_movil character varying(20) COLLATE pg_catalog."default",
    url_linkedin character varying(500) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    rol character varying(20) COLLATE pg_catalog."default" NOT NULL,
    url_foto character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT perfiles_usuario_pkey PRIMARY KEY (id),
    CONSTRAINT perfiles_usuario_usuario_id_key UNIQUE (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.sectores
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sectores_pkey PRIMARY KEY (id),
    CONSTRAINT sectores_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.temas
(
    id bigserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT temas_pkey PRIMARY KEY (id),
    CONSTRAINT temas_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigserial NOT NULL,
    correo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hash_password character varying(255) COLLATE pg_catalog."default",
    nombre_completo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_usuario character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now(),
    activo boolean DEFAULT true,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_correo_key UNIQUE (correo)
);

ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_citas_mentor
    ON public.citas(mentor_id);


ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_usuario_mentee_id_fkey FOREIGN KEY (usuario_mentee_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_citas_mentee
    ON public.citas(usuario_mentee_id);


ALTER TABLE IF EXISTS public.destacado_solicitudes
    ADD CONSTRAINT destacado_solicitudes_mentor_perfil_id_fkey FOREIGN KEY (mentor_perfil_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.disponibilidad_mentor
    ADD CONSTRAINT disponibilidad_mentor_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.educacion_usuario
    ADD CONSTRAINT educacion_usuario_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mentor_area
    ADD CONSTRAINT mentor_area_area_id_fkey FOREIGN KEY (area_id)
    REFERENCES public.areas_funcion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_area_area
    ON public.mentor_area(area_id);


ALTER TABLE IF EXISTS public.mentor_area
    ADD CONSTRAINT mentor_area_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mentor_grado
    ADD CONSTRAINT mentor_grado_grado_id_fkey FOREIGN KEY (grado_id)
    REFERENCES public.grados_academicos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_grado_grado
    ON public.mentor_grado(grado_id);


ALTER TABLE IF EXISTS public.mentor_grado
    ADD CONSTRAINT mentor_grado_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mentor_sector
    ADD CONSTRAINT mentor_sector_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mentor_sector
    ADD CONSTRAINT mentor_sector_sector_id_fkey FOREIGN KEY (sector_id)
    REFERENCES public.sectores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_sector_sector
    ON public.mentor_sector(sector_id);


ALTER TABLE IF EXISTS public.mentor_tema
    ADD CONSTRAINT mentor_tema_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES public.perfiles_mentor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mentor_tema
    ADD CONSTRAINT mentor_tema_tema_id_fkey FOREIGN KEY (tema_id)
    REFERENCES public.temas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_tema_tema
    ON public.mentor_tema(tema_id);


ALTER TABLE IF EXISTS public.perfiles_mentor
    ADD CONSTRAINT perfiles_mentor_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS perfiles_mentor_usuario_id_key
    ON public.perfiles_mentor(usuario_id);


ALTER TABLE IF EXISTS public.perfiles_usuario
    ADD CONSTRAINT perfiles_usuario_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS perfiles_usuario_usuario_id_key
    ON public.perfiles_usuario(usuario_id);

END;